[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "gunicorn --bind 0.0.0.0:8080 --workers 2 --threads 4 --timeout 120 app:app"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicy = "on-failure"

[[services]]
name = "web"
